### ISSUE TITLE
Very cool project

### ISSUE THREAD

**Issue by aarongustafson** [mor10/semaphore#1]
Can you make it work without JavaScript? That’s a core requirement of the contest.

**Comment by mor10** [comment]
I'm confused. I thought the requirements stated you couldn't use JavaScript libraries, not JavaScript itself. This is just pure JS. In the FAQ it says 

"the following will count against your 10kB:
Your HTML document;
- Any link-ed and/or @import-ed CSS;
- Any linked (via an inline script) JavaScript file;"

Most of the more advanced projects in the gallery use JavaScript. Please explain.

**Comment by mor10** [comment]
Belay that. It's only mentioned on the front page and I somehow missed it! Got too caught up in the possibilities of SVG. Baby brain and all that. 

I have been AFK for the last three days, but give me a few hours and I'll whip up an acceptable fallback.

**Comment by mor10** [comment]
@aarongustafson I've added a basic noJS fallback solution for the site. With gzipping of the referenced SVG this should compress well below 10k. Hopefully I'm not too late in submitting this fix! Paternity leave has kept me away from the computer this week.

**Comment by aarongustafson** [comment]
LOVE the fallback!!!
